import { useEffect, useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from '../services/api';

function StockCard({ market, featured = false }) {
  return <div className={featured ? 'col-12' : 'col-xl-4 col-md-6'}><div className="card shadow-sm h-100"><div className="card-body"><div className="d-flex justify-content-between"><h4>{market.symbol}</h4><span className={market.change >= 0 ? 'text-success' : 'text-danger'}>{market.change >= 0 ? '+' : ''}{market.change}%</span></div><div className="h3">${market.latest}</div><small className="text-body-secondary">Close: {market.updated}</small><div style={{ height: featured ? 300 : 180 }}><ResponsiveContainer width="100%" height="100%"><LineChart data={market.series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day" hide={!featured}/><YAxis domain={['auto', 'auto']} hide={!featured}/><Tooltip/><Line type="monotone" dataKey="value" stroke="#6f42c1" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></div></div></div>;
}

export default function Market() {
  const [markets, setMarkets] = useState([]); const [custom, setCustom] = useState(null); const [symbol, setSymbol] = useState(''); const [error, setError] = useState(''); const [searching, setSearching] = useState(false);
  useEffect(() => { api.get('/market/overview').then(({ data }) => setMarkets(data.markets)).catch(requestError => setError(requestError.response?.data?.detail || 'Market data is temporarily unavailable.')); }, []);
  const search = async event => { event.preventDefault(); if (!symbol.trim()) return; setSearching(true); setError(''); try { const { data } = await api.get('/market', { params: { symbol: symbol.trim().toUpperCase() } }); setCustom(data); } catch (requestError) { setCustom(null); setError(requestError.response?.data?.detail || 'Stock not found. Enter a valid ticker symbol.'); } finally { setSearching(false); } };
  return <div><div className="mb-4"><h1 className="h2 fw-bold">Market Analysis</h1><p className="text-body-secondary">Major US stocks from Alpha Vantage. Results are cached for five minutes to respect the free API limit.</p></div><form className="card shadow-sm mb-4" onSubmit={search}><div className="card-body d-flex flex-wrap gap-2 align-items-center"><label className="fw-semibold">Search any stock</label><input className="form-control flex-grow-1" style={{ minWidth: 220 }} value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Ticker symbol, e.g. NFLX, GOOGL, BABA"/><button className="btn btn-primary" disabled={searching}>{searching ? 'Loading…' : 'Show chart'}</button></div></form>{error && <div className="alert alert-warning">{error}</div>}{custom && <><h5 className="mb-3">Search result</h5><div className="row g-4 mb-4"><StockCard market={custom} featured /></div></>}<h5 className="mb-3">Major stocks</h5><div className="row g-4">{markets.map(market => <StockCard key={market.symbol} market={market}/>)}</div></div>;
}